name: Checks

on:
    push:
    pull_request:

jobs:
    types:
        runs-on: ubuntu-22.04
        name: Check Types

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                version: latest
                run_install: false
            - uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"
                  cache: 'pnpm'

            - run: pnpm install
            - run: pnpm types

    lint:
        runs-on: ubuntu-22.04
        name: Check Linting

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                version: latest
                run_install: false
            - uses: actions/setup-node@v4
              with:
                    node-version: "lts/*"
                    cache: 'pnpm'

            - run: pnpm install
            - run: pnpm lint

    tests:
        runs-on: ubuntu-22.04
        name: Test
        needs: [types, lint]

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                version: latest
                run_install: false
            - uses: actions/setup-node@v4
              with:
                    node-version: "lts/*"
                    cache: 'pnpm'

            - run: pnpm install
            - run: CI=TRUE pnpm test

            - uses: codecov/codecov-action@v4.5.0
              name: Upload code coverage
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                directory: ./coverage
                fail_ci_if_error: true

            - uses: codecov/test-results-action@v1
              name: Upload test results
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                fail_ci_if_error: true
